name: Test Cache download failure
on:
  workflow_dispatch:
  schedule:
  - cron: "*/10 * * * *"
jobs:
  java-example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - path: java-example
          - path: java-example/spring-boot/morphological-analyis/kuromoji
          - path: java-example/spring-boot/spring-boot-cassandra
          - path: java-example/spring-boot/spring-boot-data-dynamodb
          - path: java-example/spring-boot/spring-boot-data-jpa-example
          - path: java-example/spring-boot/spring-boot-data-jpa-query-example
          - path: java-example/spring-boot/spring-data-jpa-async/spring-data-jpa-async
          - path: java-example/spring-boot/spring-boot-jdbc-example
          - path: java-example/spring-boot/spring-boot-jdbi-example
          - path: java-example/spring-boot/spring-boot-jpa-example
          - path: java-example/spring-boot/spring-boot-metrics
          - path: java-example/spring-boot/spring-boot-micrometer
          - path: java-example/spring-boot/spring-boot-web-example
          - path: java-example/spring-boot/spring-boot-web-thymeleaf-example
          - path: java-example/spring-boot/webauthn/server
        java_versions:
          - 11
          - 17
    steps:
    - uses: kotewar/cache@a76bf59e970ccf9dda7987aced73a30029bda0aa
      id: cache
      with:
        path: /tmp/datacache
        key: cache_0610_04
      env:
        AZURE_LOG_LEVEL: info
    - if: steps.cache.outputs.cache-hit != 'true'
      run: |
        rm -rf /tmp/datacache
        mkdir -p /tmp/datacache
        for y in {0..55};do openssl rand -out /tmp/datacache/data$y  -base64 $(( 50 * 2**20 * 3/4 )); done 
        du -sh /tmp/datacache
